# Generated by Django 3.2.3 on 2021-06-12 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExamApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lastname',
            new_name='alias',
        ),
    ]
