# Generated by Django 3.2.3 on 2021-05-23 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authers_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authors',
            name='books',
        ),
        migrations.AddField(
            model_name='authors',
            name='book',
            field=models.ManyToManyField(related_name='uther', to='books_authers_app.Books'),
        ),
    ]
