# Generated by Django 3.2.3 on 2021-05-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authers_app', '0002_auto_20210523_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='desc',
            field=models.TextField(blank=True),
        ),
    ]
