# Generated by Django 3.2.3 on 2021-05-23 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authers_app', '0003_books_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='authors',
            name='book',
            field=models.ManyToManyField(related_name='Auther', to='books_authers_app.Books'),
        ),
    ]
