# Generated by Django 3.2.3 on 2021-05-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authers_app', '0004_auto_20210523_1824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='notes',
        ),
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
